name: Check domains

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
    inputs:
      ssl_threshold:
        description: "Days before SSL/WHOIS expiration to trigger an alert"
        required: false
        default: "30"
      response_time:
        description: "HTTP response time in ms to trigger an alert"
        required: false
        default: "1000"
  
permissions:
  contents: write
  issues: write

jobs:
  update-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Generate config.json
        run: |
          mkdir -p status
          REPO="${{ github.repository }}"
          BRANCH="${{ github.ref_name }}"
          USER="${REPO%%/*}"
          REPO_NAME="${REPO##*/}"
          cat <<EOF > status/config.json
          {
            "github_user": "$USER",
            "github_repo": "$REPO_NAME",
            "github_branch": "$BRANCH"
          }
          EOF
          echo "Generated status/config.json: "
          cat status/config.json

      - name: Check domains
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          RESPONSE_THRESHOLD: ${{ github.event.inputs.response_time || '1000' }}
          DAYS_THRESHOLD: ${{ github.event.inputs.ssl_threshold || '30' }}
        run: python check_domains.py

      - name: Commit files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add status/status.json
          git add status/config.json
          git add status/history/*.json
          git commit -m "Data fetched [skip ci]" || echo "No changes"
          git push
